name: Schedule Merge Contacts

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:

jobs:
  call-vercel-function:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel Function
        run: |
          curl -X GET "https://vercel.com/formx-automations-platform/duplicate-handling-monday-com"
